[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "job_scraping"
version = "0.1"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"